java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &
java -cp .:lib/* Client netprog1.csit.rmit.edu.au 51900 t t &